require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CombinedImagesController do

  # This should return the minimal set of attributes required to create a valid
  # CombinedImage. As you add validations to CombinedImage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CombinedImagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all combined_images as @combined_images" do
      combined_image = CombinedImage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:combined_images).should eq([combined_image])
    end
  end

  describe "GET show" do
    it "assigns the requested combined_image as @combined_image" do
      combined_image = CombinedImage.create! valid_attributes
      get :show, {:id => combined_image.to_param}, valid_session
      assigns(:combined_image).should eq(combined_image)
    end
  end

  describe "GET new" do
    it "assigns a new combined_image as @combined_image" do
      get :new, {}, valid_session
      assigns(:combined_image).should be_a_new(CombinedImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested combined_image as @combined_image" do
      combined_image = CombinedImage.create! valid_attributes
      get :edit, {:id => combined_image.to_param}, valid_session
      assigns(:combined_image).should eq(combined_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CombinedImage" do
        expect {
          post :create, {:combined_image => valid_attributes}, valid_session
        }.to change(CombinedImage, :count).by(1)
      end

      it "assigns a newly created combined_image as @combined_image" do
        post :create, {:combined_image => valid_attributes}, valid_session
        assigns(:combined_image).should be_a(CombinedImage)
        assigns(:combined_image).should be_persisted
      end

      it "redirects to the created combined_image" do
        post :create, {:combined_image => valid_attributes}, valid_session
        response.should redirect_to(CombinedImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved combined_image as @combined_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        CombinedImage.any_instance.stub(:save).and_return(false)
        post :create, {:combined_image => {}}, valid_session
        assigns(:combined_image).should be_a_new(CombinedImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CombinedImage.any_instance.stub(:save).and_return(false)
        post :create, {:combined_image => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested combined_image" do
        combined_image = CombinedImage.create! valid_attributes
        # Assuming there are no other combined_images in the database, this
        # specifies that the CombinedImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CombinedImage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => combined_image.to_param, :combined_image => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested combined_image as @combined_image" do
        combined_image = CombinedImage.create! valid_attributes
        put :update, {:id => combined_image.to_param, :combined_image => valid_attributes}, valid_session
        assigns(:combined_image).should eq(combined_image)
      end

      it "redirects to the combined_image" do
        combined_image = CombinedImage.create! valid_attributes
        put :update, {:id => combined_image.to_param, :combined_image => valid_attributes}, valid_session
        response.should redirect_to(combined_image)
      end
    end

    describe "with invalid params" do
      it "assigns the combined_image as @combined_image" do
        combined_image = CombinedImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CombinedImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => combined_image.to_param, :combined_image => {}}, valid_session
        assigns(:combined_image).should eq(combined_image)
      end

      it "re-renders the 'edit' template" do
        combined_image = CombinedImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CombinedImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => combined_image.to_param, :combined_image => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested combined_image" do
      combined_image = CombinedImage.create! valid_attributes
      expect {
        delete :destroy, {:id => combined_image.to_param}, valid_session
      }.to change(CombinedImage, :count).by(-1)
    end

    it "redirects to the combined_images list" do
      combined_image = CombinedImage.create! valid_attributes
      delete :destroy, {:id => combined_image.to_param}, valid_session
      response.should redirect_to(combined_images_url)
    end
  end

end
